<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActValve2_Analog" Id="{0c513952-fd68-4c45-baaf-592a4fbeeaee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActValve2_Analog EXTENDS PAEActuator2way_Analog
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActValve2_Analog">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>