<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActValve2_In" Id="{e7e7a7dc-4ec7-48cc-ae23-3485082ea6d0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActValve2_In EXTENDS PAEActuator2way_In
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActValve2_In">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>