<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActDiverter" Id="{e69dc658-0ccb-4ee7-b5c2-3b9ef93e7d53}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActDiverter EXTENDS PAEActuator2way_In
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActDiverter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>