<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActMixingValve" Id="{fd1cd2b8-5582-4c3f-8213-b0d131d14be4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActMixingValve EXTENDS PAEActuator2way_Analog
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActMixingValve">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>