<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActFlap2" Id="{d3d11179-ed49-4ee7-8d42-35700e302c65}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActFlap2 EXTENDS PAEActuator2way
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActFlap2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>