<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEGeneric" Id="{09a736cd-0b6b-4216-80b2-5fe700dd94bd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEGeneric EXTENDS PAModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEGeneric">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>