<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActValve3" Id="{e6651301-b59d-4be3-8af8-554efbcae8cf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActValve3 EXTENDS PAEActuator3way
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEActValve3">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>