<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActValve2_1plus2" Id="{6de9fff4-e55b-4a36-9dac-bd7d8de4a28d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActValve2_1plus2 EXTENDS PAEActuator2way_1plus2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="PAEActValve2_1plus2" Id="{764986e2-9d94-45e9-a9ce-b8e441ea8db5}">
      <Declaration><![CDATA[METHOD PUBLIC PAEActValve2_1plus2
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PAEActValve2_1plus2">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAEActValve2_1plus2.PAEActValve2_1plus2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>