<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActFlap" Id="{496459d0-1036-4764-ab4a-0abe57fdc608}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActFlap EXTENDS PAEActuator1way
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="PAEActFlap" Id="{fcb52c5d-c9df-4994-aa32-98d559cbdd9d}">
      <Declaration><![CDATA[METHOD PUBLIC PAEActFlap
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PAEActFlap">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAEActFlap.PAEActFlap">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>