<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEActSlider" Id="{0512d245-df30-415f-b9ad-faab750d638c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEActSlider EXTENDS PAEActuator1way
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="PAEActSlider" Id="{d2fa6bbd-253f-4eaa-8fc0-af1229425ca7}">
      <Declaration><![CDATA[METHOD PUBLIC PAEActSlider
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PAEActSlider">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAEActSlider.PAEActSlider">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>