<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEChainConveyor" Id="{5f28b255-3cb9-49e0-975d-3e702a8ae4cd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEChainConveyor EXTENDS PAETransport
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEChainConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>