<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEElevator" Id="{6d6b7513-06e2-46f7-a163-9a60ec1ee371}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEElevator EXTENDS PAETransport
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEElevator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>