<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEPump" Id="{7a66110a-4a7e-46dc-9b32-a364f5508800}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEPump EXTENDS PAEEMotor1D
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEPump">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>