<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEScrew" Id="{9472cbb9-9085-4b47-8d27-6812fb4a4a62}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEScrew EXTENDS PAETransport
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEScrew">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>