<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAClassAlarmingBase" Id="{17c5b712-7c4d-410f-bfb8-3d09306de874}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAClassAlarmingBase EXTENDS ACComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAClassAlarmingBase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>