<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAMExtruder" Id="{c6305f97-0e2d-46c7-9513-5c6bd57f091e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAMExtruder EXTENDS PAProcessModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_PAPointMatIn1 : PAPoint(THIS^);
	_PAPointMatOut1 : PAPoint(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{895be0b0-0e16-444c-aa7a-b181b80236c2}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	parent : IACComponent;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddPoint(_PAPointMatIn1);
AddPoint(_PAPointMatOut1);]]></ST>
      </Implementation>
    </Method>
    <Property Name="PAPointMatIn1" Id="{592395ca-2542-46ff-9056-9bd0639b4f9c}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatIn1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{e070da51-8067-4870-906d-0e0aa6a6a601}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatIn1 := _PAPointMatIn1;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="PAPointMatOut1" Id="{a1b4aedf-8be1-4705-b55b-cc0b762b8599}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatOut1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{54cb1ad4-e3d7-4f2d-b31c-333696c7b4a4}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatOut1 := _PAPointMatOut1;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="PAMExtruder">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAMExtruder.FB_init">
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="PAMExtruder.PAPointMatIn1.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="PAMExtruder.PAPointMatOut1.Get">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>