<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAMHopperscale" Id="{e641740c-06ba-466d-a5e6-22d0379ea510}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAMHopperscale EXTENDS PAProcessModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_PAPointMatIn1 : PAPoint(THIS^);
	_PAPointMatOut1 : PAPoint(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{a93a8873-ca21-4dcb-8d67-c54595bfe395}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	parent : IACComponent;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddPoint(_PAPointMatIn1);
AddPoint(_PAPointMatOut1);]]></ST>
      </Implementation>
    </Method>
    <Property Name="PAPointMatIn1" Id="{b129d6bf-1558-4cba-909a-6de1937430db}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatIn1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{251488a2-4af2-49a3-92d5-9467ac666da7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatIn1 := _PAPointMatIn1;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="PAPointMatOut1" Id="{bb66304f-bcb1-4c90-a930-a8753194ae4f}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatOut1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{7637d192-0cee-4495-8020-9b4110b6a476}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatOut1 := _PAPointMatOut1;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="PAMHopperscale">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAMHopperscale.FB_init">
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="PAMHopperscale.PAPointMatIn1.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="PAMHopperscale.PAPointMatOut1.Get">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>