<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAMIntake" Id="{cac1cf61-6858-4557-b7b9-1aa9b8cdf323}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAMIntake EXTENDS PAMLoadingstation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAMIntake">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>