<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAMLoadingstation" Id="{d10887e0-b2aa-49bf-80a1-553cc1de3c8d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAMLoadingstation EXTENDS PAProcessModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_PAPointMatIn1 : PAPoint(THIS^);
	_PAPointMatOut1 : PAPoint(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{2219036e-ca6b-42bb-ad50-e3b1c446d834}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	parent : IACComponent;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddPoint(_PAPointMatIn1);
AddPoint(_PAPointMatOut1);]]></ST>
      </Implementation>
    </Method>
    <Property Name="PAPointMatIn1" Id="{a80cd1b8-832a-43c0-aee7-5170e4bcdd30}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatIn1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{fb76a11d-fcb8-4205-85cd-2c7f13e59b0d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatIn1 := _PAPointMatIn1;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="PAPointMatOut1" Id="{b4c814ed-2165-4b8b-adaa-75fa11c19ed9}">
      <Declaration><![CDATA[PROPERTY PUBLIC PAPointMatOut1 : IACPoint]]></Declaration>
      <Get Name="Get" Id="{f4d6fc9d-e0e8-4060-931b-76ed5516d2a0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PAPointMatOut1 := _PAPointMatOut1;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="PAMLoadingstation">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PAMLoadingstation.FB_init">
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="PAMLoadingstation.PAPointMatIn1.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="PAMLoadingstation.PAPointMatOut1.Get">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>