<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAEConveyorBelt" Id="{2f107bde-db07-4cea-888d-183fe8c7622e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAEConveyorBelt EXTENDS PAEElevator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAEConveyorBelt">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>