<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="PAModule" Id="{2c897f2d-db84-43c4-bcce-3e608c724a80}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PAModule EXTENDS PAClassPhysicalBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PAModule">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>