<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="ApplicationManager" Id="{b0d12743-9b42-4cee-8ff9-bcbf4e85167d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ApplicationManager EXTENDS PAClassAlarmingBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ApplicationManager">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>